ClientEvents.lang('en_us', event => {
  event.renameItem("herbalexpansion:fresh_blue_dream_nug", "§bFresh Blue Dream Nug")
  event.renameItem("herbalexpansion:dried_blue_dream_nug", "§bDried Blue Dream Nug")
  event.renameItem("herbalexpansion:blue_dream_oil", "§bBlue Dream Oil")
  event.renameItem("herbalexpansion:fresh_girl_scout_cookies_nug", "§dFresh Girl Scout Cookies Nug")
  event.renameItem("herbalexpansion:dried_girl_scout_cookies_nug", "§dDried Girl Scout Cookies Nug")
  event.renameItem("herbalexpansion:girl_scout_cookies_oil", "§dGirl Scout Cookies Oil")
  event.renameItem("herbalexpansion:fresh_lemon_haze_nug", "§eFresh Lemon Haze Nug")
  event.renameItem("herbalexpansion:dried_lemon_haze_nug", "§eDried Lemon Haze Nug")
  event.renameItem("herbalexpansion:lemon_haze_oil", "§eLemon Haze Oil")
  event.renameItem("herbalexpansion:fresh_northern_lights_nug", "§2Fresh Northern Lights Nug")
  event.renameItem("herbalexpansion:dried_northern_lights_nug", "§2Dried Northern Lights Nug")
  event.renameItem("herbalexpansion:northern_lights_oil", "§2Northern Lights Oil")
  event.renameItem("herbalexpansion:fresh_panama_red_nug", "§cFresh Panama Red Nug")
  event.renameItem("herbalexpansion:dried_panama_red_nug", "§cDried Panama Red Nug")
  event.renameItem("herbalexpansion:panama_red_oil", "§cPanama Red Oil")
  event.renameItem("herbalexpansion:fresh_purple_haze_nug", "§5Fresh Purple Haze Nug")
  event.renameItem("herbalexpansion:dried_purple_haze_nug", "§5Dried Purple Haze Nug")
  event.renameItem("herbalexpansion:purple_haze_oil", "§5Purple Haze Oil")
  event.renameItem("herbalexpansion:fresh_sour_diesel_nug", "§6Fresh Sour Diesel Nug")
  event.renameItem("herbalexpansion:dried_sour_diesel_nug", "§6Dried Sour Diesel Nug")
  event.renameItem("herbalexpansion:sour_diesel_oil", "§6Sour Diesel Oil")
  event.renameItem("herbalexpansion:fresh_white_widow_nug", "§fFresh White Widow Nug")
  event.renameItem("herbalexpansion:dried_white_widow_nug", "§fDried White Widow Nug")
  event.renameItem("herbalexpansion:white_widow_oil", "§fWhite Widow Oil")
  event.renameItem("herbalexpansion:blue_dream_joint", "§bBlue Dream Joint")
  event.renameItem("herbalexpansion:girl_scout_cookies_joint", "§dGirl Scout Cookies Joint")
  event.renameItem("herbalexpansion:lemon_haze_joint", "§eLemon Haze Joint")
  event.renameItem("herbalexpansion:northern_lights_joint", "§2Northern Lights Joint")
  event.renameItem("herbalexpansion:panama_red_joint", "§cPanama Red Joint")
  event.renameItem("herbalexpansion:purple_haze_joint", "§5Purple Haze Joint")
  event.renameItem("herbalexpansion:sour_diesel_joint", "§6Sour Diesel Joint")
  event.renameItem("herbalexpansion:white_widow_joint", "§fWhite Widow Joint")
})